# 测试配置文件
# @author <a href="https://github.com/weedsx">weeds</a>
#
server:
  port: 8180
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_api
    username: root
    password: llh112358
  # Redis 配置
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000
  # Elasticsearch 配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456

# 仅供测试，真实环境是从数据库中查询用户的 ak、sk
# open-api:
#   client:
#     access-key: weeds
#     secret-key: 123456

# dubbo 配置
dubbo:
  application:
    name: open-api-core
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
    enable-file-cache: false
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: open-api-core
    address: nacos://localhost:8848